[package]
name = "bruteforcer-cli"
version = "0.1.0"
authors = ["TNkemdilim"]

[dependencies]
clap = { version = "2.31.2", features = ["yaml"] }
rustify_bruteforcer = { path = "../../../rustify_bruteforcer" }